#!/bin/bash
set -x
set -eo pipefail

# We now run the assembly script. If there is a custom one written in the
# source files, we use that instead.
if [ -f /opt/app-root/src/.s2i/bin/assemble ]; then
    /opt/app-root/src/.s2i/bin/assemble
elif [ -f /usr/local/s2i/assemble ]; then # java s2i
    rm -rf /opt/app-root/src/.git # ensure we don't copy git files since they can cause problems
    cp -a /opt/app-root/src/. /tmp/src # java s2i expects the source to be under /tmp/src
    /usr/local/s2i/assemble
else
    /usr/libexec/s2i/assemble
fi

# Restart supervisord in order to actualy run the application
# This is a dumb way to start as supervisord does not have a restart function
/var/lib/supervisord/bin/supervisord ctl stop run; /var/lib/supervisord/bin/supervisord ctl start run
