#!/bin/bash
set -x
set -eo pipefail

# We now run the assembly script. If there is a custom one written in the
# source files, we use that instead.
if [ -f ${ODO_S2I_SRC_BIN_PATH}/.s2i/bin/assemble ]; then
    ${ODO_S2I_SRC_BIN_PATH}/.s2i/bin/assemble
elif [ -n "${ODO_S2I_SCRIPTS_URL}" ]; then # For S2I scripts path, use the env var set by odo if not available in component source
    rm -rf /opt/app-root/src/.git # ensure we don't copy git files since they can cause problems
    ${ODO_S2I_SCRIPTS_URL}/assemble
else
    /usr/libexec/s2i/assemble
fi

### 
# Check "ODO_S2I_DEPLOYMENT_DIR" environment variable and if it's present,
# copy content of directory to /opt/app-root/backup directory
# Ref: https://github.com/redhat-developer/odo/issues/445
if [ -n "$ODO_S2I_DEPLOYMENT_DIR" ]; then
    if [ ! -d /opt/app-root/backup ]; then
        mkdir -p /opt/app-root/backup
    fi
   cp -rf ${ODO_S2I_DEPLOYMENT_DIR}/* /opt/app-root/backup/
fi
####

# Restart supervisord in order to actualy run the application
# This is a dumb way to start as supervisord does not have a restart function
/var/lib/supervisord/bin/supervisord ctl stop run; /var/lib/supervisord/bin/supervisord ctl start run
