#!/bin/bash
set -x
set -eo pipefail

###
# Check "ODO_S2I_DEPLOYMENT_DIR" environment variable and if it's present,
# copy content from /opt/app-root/backup directory to "ODO_S2I_DEPLOYMENT_DIR"
# Ref: https://github.com/redhat-developer/odo/issues/445
if [ -n "$ODO_S2I_DEPLOYMENT_DIR" ]; then
    cp -rf /opt/app-root/backup/* ${ODO_S2I_DEPLOYMENT_DIR}/
fi
###

# We now run the run script. If there is a custom one written in the
# source files, we use that instead.
if [ -f ${ODO_S2I_SRC_BIN_PATH}/.s2i/bin/run ]; then
    exec ${ODO_S2I_SRC_BIN_PATH}/.s2i/bin/run
elif [ -f ${ODO_S2I_SCRIPTS_URL}/run ]; then # java s2i
    exec ${ODO_S2I_SCRIPTS_URL}/run
else
    exec /usr/libexec/s2i/run
fi
