#!/bin/bash
set -e
set -x

cd /tmp/src


NPM_RUN="${NPM_RUN:=start}"
NODE_ENV="${NODE_ENV:=development}"


export GIT_COMMITTER_NAME="unknown"
export and GIT_COMMITTER_EMAIL="unknown@localhost.com"
git --version

echo -e "Using Node.js version: $(node --version)"
echo -e "Environment:"
echo -e "  NODE_ENV=${NODE_ENV}"
echo -e "Running as user $(id)"

echo "Launching via npm..."
exec npm run ${NPM_RUN}

