#!/bin/bash
set -e
set -x

DEBUG_PORT="${DEBUG_PORT:=49200}"

# DEV_MODE is true by default, which means that the application will be started with remote debugging enabled.
DEV_MODE="${DEV_MODE:=true}"

if [ $DEV_MODE != "false" ]; then
    export JAVA_OPTS="$JAVA_OPTS -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=${DEBUG_PORT},suspend=n"
    export JAVA_OPTIONS=$JAVA_OPTS
fi

# run normal run s2i script
exec "${ODO_S2I_SCRIPTS_URL}/run"